
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-{{ .Release.Name }}
  labels:
    project: counter
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      project: counter
      app: counter
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        project: counter
        app: counter
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: counter
          image: ondrejsika/counter
          resources:
            requests:
              cpu: 20m
              memory: 30Mi
            limits:
              cpu: 50m
              memory: 60Mi
          env:
            - name: REDIS
              value: redis-{{ .Release.Name }}
          ports:
            - containerPort: 80
