apiVersion: v1
kind: Service
metadata:
  name: counter-{{ .Release.Name }}
  labels:
    project: counter
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 80
  selector:
    project: counter
    app: counter
    release: {{ .Release.Name }}
