apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counter-{{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: tls-counter-{{ .Release.Name }}
  rules:
    - host: {{ required ".Values.host is required" .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: counter-{{ .Release.Name }}
                port:
                  number: 80
