apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-{{ .Release.Name }}
  labels:
    project: counter
    release: {{ .Release.Name }}
spec:
  serviceName: redis-{{ .Release.Name }}
  selector:
    matchLabels:
      project: counter
      app: redis
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: counter
        app: redis
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 30m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 80Mi
          ports:
            - containerPort: 6379
