apiVersion: v1
kind: Service
metadata:
  name: redis-{{ .Release.Name }}
  labels:
    project: counter
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 6379
  selector:
    project: counter
    app: redis
    release: {{ .Release.Name }}
